// Assemble a complete, ejectable subgraph project from the generated files and
// contract metadata, and zip it in the browser. The output goes straight through
// the canonical toolchain: `npm i` → `graph codegen` → `graph build` → `graph deploy`.

import JSZip from "jszip";
import { sanitizeName } from "./generate";
import type { GeneratedSubgraph } from "./generate";
import type { ContractInfo } from "./subgraph-abi";

function eventAbiOnly(contract: ContractInfo): string {
  // The generated types only need the ABI; ship it whole so `graph codegen` has
  // everything (events + any view fns the mappings call).
  return JSON.stringify(contract.abi, null, 2);
}

function packageJson(name: string): string {
  return JSON.stringify(
    {
      name: `${name.toLowerCase()}-subgraph`,
      version: "0.0.1",
      scripts: {
        codegen: "graph codegen",
        build: "graph build",
        deploy: "graph deploy",
        test: "graph test",
      },
      dependencies: {
        "@graphprotocol/graph-cli": "0.97.1",
        "@graphprotocol/graph-ts": "0.38.0",
      },
      devDependencies: {
        "matchstick-as": "0.6.0",
      },
    },
    null,
    2,
  );
}

const TSCONFIG = JSON.stringify(
  { extends: "@graphprotocol/graph-ts/types/tsconfig.base.json", include: ["src", "tests"] },
  null,
  2,
);

const CI_WORKFLOW = `name: subgraph
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm install
      - run: npm run codegen
      - run: npm run build
      - run: npm run test
`;

function readme(name: string, contract: ContractInfo): string {
  return `# ${name} subgraph

Generated by [The Generator](https://redstart-lang.com/generator) from
\`${contract.address}\` on \`${contract.graphNetwork}\`. Plain, portable AssemblyScript —
you own it, deploy it anywhere.

## Deploy to Subgraph Studio

\`\`\`bash
npm install
npx graph auth <DEPLOY_KEY>        # from your Studio subgraph page
npm run codegen && npm run build
npx graph deploy <SUBGRAPH_SLUG>   # deploys to Studio (private), pick a version e.g. 0.0.1
\`\`\`

Create the Studio subgraph first at [thegraph.com/studio](https://thegraph.com/studio)
(connect a wallet, "Create a Subgraph", copy the deploy key). Deploying pushes to
Studio for testing; publishing on-chain is a separate step.
`;
}

/** Build the file map for the project. */
export function projectFiles(
  files: GeneratedSubgraph,
  contract: ContractInfo,
): Record<string, string> {
  const name = sanitizeName(contract.name);
  return {
    "schema.graphql": files.schema,
    "subgraph.yaml": files.manifest,
    "src/mapping.ts": files.mappings,
    [`tests/${name.toLowerCase()}.test.ts`]: files.tests,
    "tests/utils.ts": files.testUtils,
    [`abis/${name}.json`]: eventAbiOnly(contract),
    "package.json": packageJson(name),
    "tsconfig.json": TSCONFIG,
    ".github/workflows/subgraph.yml": CI_WORKFLOW,
    "README.md": readme(name, contract),
  };
}

/** The subset the verifier accepts: schema, manifest, mappings, ABI. */
export function verifiableFiles(
  files: GeneratedSubgraph,
  contract: ContractInfo,
): Record<string, string> {
  const name = sanitizeName(contract.name);
  return {
    "schema.graphql": files.schema,
    "subgraph.yaml": files.manifest,
    "src/mapping.ts": files.mappings,
    [`abis/${name}.json`]: eventAbiOnly(contract),
  };
}

export interface VerifyResult {
  ok: boolean;
  stage: string;
  log?: string;
  error?: string;
  timedOut?: boolean;
}

/** Ask the sandbox whether the generated subgraph compiles. */
export async function verifyProject(
  files: GeneratedSubgraph,
  contract: ContractInfo,
): Promise<VerifyResult> {
  const res = await fetch("/api/verify", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ files: verifiableFiles(files, contract) }),
  });
  return (await res.json()) as VerifyResult;
}

/** Zip the project and trigger a browser download. */
export async function downloadProject(
  files: GeneratedSubgraph,
  contract: ContractInfo,
): Promise<void> {
  const zip = new JSZip();
  const map = projectFiles(files, contract);
  for (const [path, content] of Object.entries(map)) {
    zip.file(path, content);
  }
  const blob = await zip.generateAsync({ type: "blob" });
  const name = sanitizeName(contract.name).toLowerCase();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name}-subgraph.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
