//! Generates `subgraph.yaml` from Redstart `source`/`template`/`handler`
//! declarations.
//!
//! Because handlers bind to ABI events *by reference* (`handler on Src.Event`),
//! the manifest's `eventHandlers` list is derived, not hand-maintained — the
//! string-typed coupling that causes manifest/handler drift today is gone.

use crate::abi::AbiIndex;
use redstart_parser::ast::{Expr, HandlerDecl, Setting, SourceDecl, TemplateDecl};

/// The spec version emitted. Redstart owns this so the developer never touches
/// the `specVersion`/`apiVersion` compatibility matrix.
const SPEC_VERSION: &str = "1.0.0";
const API_VERSION: &str = "0.0.9";

/// Inputs for manifest generation.
pub struct ManifestInput<'a> {
    /// The subgraph name/description.
    pub name: &'a str,
    /// Optional description.
    pub description: Option<&'a str>,
    /// All data sources.
    pub sources: &'a [&'a SourceDecl],
    /// All templates.
    pub templates: &'a [&'a TemplateDecl],
    /// All handlers.
    pub handlers: &'a [&'a HandlerDecl],
    /// All entity names (declared in the schema).
    pub entity_names: &'a [String],
}

/// Render `subgraph.yaml`, collecting any warnings (e.g. unresolved signatures).
#[must_use]
pub fn render(input: &ManifestInput, abi_index: &mut AbiIndex) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings = Vec::new();

    out.push_str("# Generated by Redstart — do not edit by hand.\n");
    out.push_str(&format!("specVersion: {SPEC_VERSION}\n"));
    if let Some(desc) = input.description {
        out.push_str(&format!("description: {desc}\n"));
    }
    out.push_str(&format!("# subgraph: {}\n", input.name));
    out.push_str("schema:\n  file: ./schema.graphql\n");

    out.push_str("dataSources:\n");
    for source in input.sources {
        render_data_source(&mut out, source, input, abi_index, &mut warnings);
    }

    if !input.templates.is_empty() {
        out.push_str("templates:\n");
        for template in input.templates {
            render_template(&mut out, template, input, abi_index, &mut warnings);
        }
    }

    (out, warnings)
}

fn render_data_source(
    out: &mut String,
    source: &SourceDecl,
    input: &ManifestInput,
    abi_index: &mut AbiIndex,
    warnings: &mut Vec<String>,
) {
    let abi = setting_str(&source.settings, "abi").unwrap_or_else(|| "Contract".to_string());
    let network =
        setting_str(&source.settings, "network").unwrap_or_else(|| "mainnet".to_string());
    let address = setting_str(&source.settings, "address").unwrap_or_default();
    let start_block = setting_str(&source.settings, "startBlock").unwrap_or_else(|| "0".to_string());

    out.push_str(&format!("  - kind: ethereum\n    name: {}\n", source.name.name));
    out.push_str(&format!("    network: {network}\n"));
    out.push_str("    source:\n");
    out.push_str(&format!("      address: \"{address}\"\n"));
    out.push_str(&format!("      abi: {abi}\n"));
    out.push_str(&format!("      startBlock: {start_block}\n"));

    render_mapping(out, &source.name.name, &abi, input, abi_index, warnings);
}

fn render_template(
    out: &mut String,
    template: &TemplateDecl,
    input: &ManifestInput,
    abi_index: &mut AbiIndex,
    warnings: &mut Vec<String>,
) {
    let abi = setting_str(&template.settings, "abi").unwrap_or_else(|| "Contract".to_string());
    let network =
        setting_str(&template.settings, "network").unwrap_or_else(|| "mainnet".to_string());

    out.push_str(&format!(
        "  - kind: ethereum\n    name: {}\n",
        template.name.name
    ));
    out.push_str(&format!("    network: {network}\n"));
    out.push_str("    source:\n");
    out.push_str(&format!("      abi: {abi}\n"));

    render_mapping(out, &template.name.name, &abi, input, abi_index, warnings);
}

fn render_mapping(
    out: &mut String,
    source_name: &str,
    abi: &str,
    input: &ManifestInput,
    abi_index: &mut AbiIndex,
    warnings: &mut Vec<String>,
) {
    out.push_str("    mapping:\n      kind: ethereum/events\n");
    out.push_str(&format!("      apiVersion: {API_VERSION}\n"));
    out.push_str("      language: wasm/assemblyscript\n");

    out.push_str("      entities:\n");
    for name in input.entity_names {
        out.push_str(&format!("        - {name}\n"));
    }

    out.push_str("      abis:\n");
    // ABIs are copied into the build dir, so the manifest references them locally.
    out.push_str(&format!(
        "        - name: {abi}\n          file: ./abis/{abi}.json\n"
    ));

    out.push_str("      eventHandlers:\n");
    for handler in input.handlers.iter().filter(|h| h.source.name == source_name) {
        let handler_name = handler_fn_name(&handler.event.name);
        let signature = abi_index
            .event_signature(abi, &handler.event.name)
            .unwrap_or_else(|| {
                warnings.push(format!(
                    "could not resolve signature for event `{}` in ABI `{abi}`; \
                     emitted a placeholder",
                    handler.event.name
                ));
                format!("{}(/* TODO: resolve from ABI */)", handler.event.name)
            });
        out.push_str(&format!(
            "        - event: {signature}\n          handler: {handler_name}\n"
        ));
    }

    out.push_str("      file: ./src/mappings.ts\n");
}

/// The AssemblyScript handler function name Redstart derives for an event.
#[must_use]
pub fn handler_fn_name(event: &str) -> String {
    format!("handle{event}")
}

/// Render a setting value to a manifest string.
fn setting_str(settings: &[Setting], key: &str) -> Option<String> {
    let setting = settings.iter().find(|s| s.key.name == key)?;
    Some(render_value(&setting.value))
}

fn render_value(expr: &Expr) -> String {
    match expr {
        Expr::Path { segments, .. } => segments
            .iter()
            .map(|s| s.name.clone())
            .collect::<Vec<_>>()
            .join("::"),
        Expr::Hex { raw, .. } | Expr::Int { raw, .. } | Expr::Decimal { raw, .. } => raw.clone(),
        Expr::Str { value, .. } => value.clone(),
        Expr::Bool { value, .. } => value.to_string(),
        _ => String::new(),
    }
}
