//! Assembles `mappings.ts` from lowered handlers plus the imports graph-ts
//! expects. The lowering itself lives in [`crate::lower`].
//!
//! Output layout matches a hand-written subgraph so the eject path is clean:
//! the file lives at `build/src/mappings.ts` and imports the `graph codegen`
//! output from `../generated/...`.

use crate::lower::{lower_handler, Env};
use redstart_parser::ast::HandlerDecl;
use std::collections::BTreeMap;

/// Render `mappings.ts` for all handlers. Returns the source and any warnings.
pub fn render(handlers: &[&HandlerDecl], entity_names: &[String], env: &mut Env) -> (String, Vec<String>) {
    let mut warnings = Vec::new();

    // Lower every handler first, so we can scan the generated code to decide
    // which graph-ts types to import.
    let mut functions = String::new();
    for handler in handlers {
        let (body, mut warns) = lower_handler(handler, env);
        warnings.append(&mut warns);
        let event_ty = format!("{}Event", handler.event.name);
        let fn_name = format!("handle{}", handler.event.name);
        functions.push_str(&format!(
            "export function {fn_name}(event: {event_ty}): void {{\n{body}}}\n\n"
        ));
    }

    let mut out = String::new();
    out.push_str("// Generated by Redstart — do not edit by hand.\n");
    out.push_str("// Eject freely: this is the AssemblyScript a careful human would write.\n\n");

    out.push_str(&render_imports(handlers, entity_names, env, &functions));
    out.push('\n');
    out.push_str(&functions);

    (out, warnings)
}

fn render_imports(
    handlers: &[&HandlerDecl],
    entity_names: &[String],
    env: &Env,
    body: &str,
) -> String {
    let mut out = String::new();

    // graph-ts scalar imports, only those actually referenced.
    let mut gts: Vec<&str> = ["BigInt", "BigDecimal", "Bytes", "Address"]
        .into_iter()
        .filter(|ty| body.contains(ty))
        .collect();
    gts.sort_unstable();
    if !gts.is_empty() {
        out.push_str(&format!(
            "import {{ {} }} from \"@graphprotocol/graph-ts\"\n",
            gts.join(", ")
        ));
    }

    // Event imports, grouped by (source, abi) module, aliased to avoid clashing
    // with an entity of the same name (e.g. a `Transfer` entity AND event).
    let mut by_module: BTreeMap<(String, String), Vec<String>> = BTreeMap::new();
    for handler in handlers {
        let abi = env
            .source_abi
            .get(&handler.source.name)
            .cloned()
            .unwrap_or_else(|| "Contract".to_string());
        by_module
            .entry((handler.source.name.clone(), abi))
            .or_default()
            .push(handler.event.name.clone());
    }
    for ((source, abi), mut events) in by_module {
        events.sort_unstable();
        events.dedup();
        let specifiers: Vec<String> = events
            .iter()
            .map(|e| format!("{e} as {e}Event"))
            .collect();
        out.push_str(&format!(
            "import {{ {} }} from \"../generated/{source}/{abi}\"\n",
            specifiers.join(", ")
        ));
    }

    // Entity imports from the generated schema.
    if !entity_names.is_empty() {
        let mut names = entity_names.to_vec();
        names.sort_unstable();
        out.push_str(&format!(
            "import {{ {} }} from \"../generated/schema\"\n",
            names.join(", ")
        ));
    }

    out
}
