//! AssemblyScript mapping generation.
//!
//! **Stage 0 status: skeleton only.** Faithful lowering of handler bodies —
//! `Option<T>` -> `T | null` with null-checks only at unwrap sites, `Result`
//! contract calls -> `try_*` + `.reverted`, `BigDecimal` operators ->
//! `.times()`/`.plus()`, auto-save dirty-tracking — is the heart of the whole
//! bet and lands in Stage 1, gated on the differential store-diff benchmark.
//!
//! For now we emit a compilable skeleton with one exported `handle*` function
//! per handler, so the full `redstart build` pipeline runs end to end and the
//! generated `subgraph.yaml` references a real file.

use crate::manifest::handler_fn_name;
use redstart_parser::ast::HandlerDecl;

/// Render the `mappings.ts` skeleton for a set of handlers.
#[must_use]
pub fn render(handlers: &[&HandlerDecl]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Redstart — do not edit by hand.\n");
    out.push_str("// Stage 0: handler bodies are not yet lowered (see redstart-codegen/mappings.rs).\n\n");

    for handler in handlers {
        let fn_name = handler_fn_name(&handler.event.name);
        let event_ty = handler.event.name.clone();
        out.push_str(&format!(
            "// from `handler on {}.{}` ({} statement(s) pending lowering)\n",
            handler.source.name,
            handler.event.name,
            handler.body.stmts.len()
        ));
        out.push_str(&format!(
            "export function {fn_name}(event: {event_ty}): void {{\n\
             \x20 // TODO: lowered from Redstart in Stage 1\n\
             }}\n\n"
        ));
    }
    out
}
