//! Assembles `mappings.ts` from lowered handlers plus the imports graph-ts
//! expects. The lowering itself lives in [`crate::lower`].
//!
//! Output layout matches a hand-written subgraph so the eject path is clean:
//! the file lives at `build/src/mappings.ts` and imports the `graph codegen`
//! output from `../generated/...`.

use crate::lower::{lower_handler, Env};
use redstart_parser::ast::{HandlerDecl, HandlerKind};
use std::collections::BTreeMap;

/// The AssemblyScript class name for a call handler's `call` parameter
/// (`graph codegen` emits `<Capitalized>Call`).
fn call_class(handler: &HandlerDecl) -> String {
    let f = &handler.event.name;
    let mut chars = f.chars();
    let cap = chars
        .next()
        .map_or_else(String::new, |c| c.to_uppercase().collect::<String>() + chars.as_str());
    format!("{cap}Call")
}

/// The parameter type annotation for a handler's binding.
fn param_type(handler: &HandlerDecl) -> String {
    match handler.kind {
        HandlerKind::Event => format!("{}Event", handler.event.name),
        HandlerKind::Call => call_class(handler),
        HandlerKind::Block(_) => "ethereum.Block".to_string(),
        HandlerKind::File => "Bytes".to_string(),
    }
}

/// Render `mappings.ts` for all handlers. Returns the source and any warnings.
pub fn render(handlers: &[&HandlerDecl], entity_names: &[String], env: &mut Env) -> (String, Vec<String>) {
    let mut warnings = Vec::new();

    // Lower every handler first, so we can scan the generated code to decide
    // which graph-ts types to import.
    let mut functions = String::new();
    for handler in handlers {
        let (body, mut warns) = lower_handler(handler, env);
        warnings.append(&mut warns);
        let pty = param_type(handler);
        let fn_name = handler.fn_name();
        let param = &handler.param.name;
        functions.push_str(&format!(
            "export function {fn_name}({param}: {pty}): void {{\n{body}}}\n\n"
        ));
    }

    let mut out = String::new();
    out.push_str("// Generated by Redstart — do not edit by hand.\n");
    out.push_str("// Eject freely: this is the AssemblyScript a careful human would write.\n\n");

    out.push_str(&render_imports(handlers, entity_names, env, &functions));
    out.push('\n');
    out.push_str(&functions);

    (out, warnings)
}

fn render_imports(
    handlers: &[&HandlerDecl],
    entity_names: &[String],
    env: &Env,
    body: &str,
) -> String {
    let mut out = String::new();

    // graph-ts imports: every top-level type/namespace actually referenced as a
    // whole word (so `log.info` imports `log` but `event.logIndex` does not).
    let gts = graph_ts_specifiers(body);
    if !gts.is_empty() {
        out.push_str(&format!(
            "import {{ {} }} from \"@graphprotocol/graph-ts\"\n",
            gts.join(", ")
        ));
    }

    // Generated-module imports, grouped by (source, abi). Event handlers import
    // the event class aliased (`Transfer as TransferEvent`) to avoid clashing
    // with an entity of the same name; call handlers import the `<Fn>Call`
    // class unaliased; block handlers import nothing from here.
    let mut by_module: BTreeMap<(String, String), Vec<String>> = BTreeMap::new();
    for handler in handlers {
        let abi = env
            .source_abi
            .get(&handler.source.name)
            .cloned()
            .unwrap_or_else(|| "Contract".to_string());
        let entry = by_module
            .entry((handler.source.name.clone(), abi))
            .or_default();
        match handler.kind {
            HandlerKind::Event => entry.push(format!("{e} as {e}Event", e = handler.event.name)),
            HandlerKind::Call => entry.push(call_class(handler)),
            HandlerKind::Block(_) | HandlerKind::File => {}
        }
    }
    for ((source, abi), mut specifiers) in by_module {
        specifiers.sort_unstable();
        specifiers.dedup();
        // If a handler binds the contract for a read call, import the contract
        // class (unaliased) first — it reads naturally before the trigger types.
        if body.contains(&format!("{abi}.bind(")) {
            specifiers.insert(0, abi.clone());
        }
        if specifiers.is_empty() {
            continue;
        }
        // `graph codegen` writes a template's ABI types under
        // `generated/templates/<Template>/<Abi>.ts`, but a regular data source's
        // under `generated/<Source>/<Abi>.ts`.
        let prefix = if env.templates.contains(&source) {
            "../generated/templates"
        } else {
            "../generated"
        };
        out.push_str(&format!(
            "import {{ {} }} from \"{prefix}/{source}/{abi}\"\n",
            specifiers.join(", ")
        ));
    }

    // Template imports from the generated `templates` module — any template the
    // handlers instantiate via `<Name>.create(...)` / `.createWithContext(...)`.
    let mut used_templates: Vec<&String> = env
        .templates
        .iter()
        .filter(|t| {
            body.contains(&format!("{t}.create("))
                || body.contains(&format!("{t}.createWithContext("))
        })
        .collect();
    used_templates.sort_unstable();
    used_templates.dedup();
    if !used_templates.is_empty() {
        let names: Vec<String> = used_templates.iter().map(|t| (*t).clone()).collect();
        out.push_str(&format!(
            "import {{ {} }} from \"../generated/templates\"\n",
            names.join(", ")
        ));
    }

    // Entity imports from the generated schema.
    if !entity_names.is_empty() {
        let mut names = entity_names.to_vec();
        names.sort_unstable();
        out.push_str(&format!(
            "import {{ {} }} from \"../generated/schema\"\n",
            names.join(", ")
        ));
    }

    out
}

/// The full set of top-level `@graphprotocol/graph-ts` exports Redstart may emit
/// — types and namespaces. Anything referenced as a whole word gets imported.
const GRAPH_TS_EXPORTS: &[&str] = &[
    // types
    "Address", "BigDecimal", "BigInt", "ByteArray", "Bytes", "DataSourceContext",
    "Entity", "TypedMap", "Value", "Wrapped",
    // namespaces
    "crypto", "dataSource", "ens", "ethereum", "ipfs", "json", "log", "store",
    "typeConversion",
];

/// Collect, sorted, the graph-ts identifiers referenced (as whole words) in the
/// lowered mapping body.
fn graph_ts_specifiers(body: &str) -> Vec<&'static str> {
    let mut found: Vec<&'static str> = GRAPH_TS_EXPORTS
        .iter()
        .copied()
        .filter(|w| references_word(body, w))
        .collect();
    found.sort_unstable();
    found
}

/// Whether `word` appears in `body` as a whole identifier — not preceded or
/// followed by an identifier character. So `log` matches in `log.info(...)` but
/// not in `event.logIndex`, and `Bytes` does not match inside `ByteArray`.
fn references_word(body: &str, word: &str) -> bool {
    let bytes = body.as_bytes();
    let mut from = 0;
    while let Some(rel) = body[from..].find(word) {
        let start = from + rel;
        let end = start + word.len();
        let before_ok = start == 0 || !is_ident_byte(bytes[start - 1]);
        let after_ok = bytes.get(end).is_none_or(|b| !is_ident_byte(*b));
        if before_ok && after_ok {
            return true;
        }
        from = start + 1;
    }
    false
}

fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

#[cfg(test)]
mod tests {
    use super::{graph_ts_specifiers, references_word};

    #[test]
    fn whole_word_matching_avoids_false_positives() {
        assert!(references_word("log.info(x)", "log"));
        assert!(!references_word("event.logIndex.toI32()", "log"));
        assert!(references_word("ByteArray.fromI32(1)", "ByteArray"));
        // `Bytes` must not match inside `ByteArray`.
        assert!(!references_word("ByteArray.fromI32(1)", "Bytes"));
        assert!(references_word("crypto.keccak256(b)", "crypto"));
        assert!(!references_word("mycrypto.x", "crypto"));
    }

    #[test]
    fn gathers_referenced_namespaces_sorted() {
        let body = "log.info(x); let h = crypto.keccak256(b); BigInt.fromI32(1)";
        assert_eq!(graph_ts_specifiers(body), vec!["BigInt", "crypto", "log"]);
    }
}
